name: Binance P2P 15-Min Collector

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Librerías
        run: pip install requests beautifulsoup4 supabase

      - name: Ejecutar Extractor
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python collector.py
